# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)


### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch
tensor = torch.rand(7, 7)

# Create random tensor
tensor

tensor([[0.7802, 0.1516, 0.9104, 0.3739, 0.2614, 0.5235, 0.2863],
        [0.9574, 0.3450, 0.3948, 0.1630, 0.2308, 0.9463, 0.4068],
        [0.2207, 0.8978, 0.6475, 0.2129, 0.0757, 0.0512, 0.0473],
        [0.8874, 0.2358, 0.3303, 0.6342, 0.0119, 0.5885, 0.8806],
        [0.7536, 0.7026, 0.5657, 0.3918, 0.7781, 0.9602, 0.8845],
        [0.5947, 0.2281, 0.3723, 0.9018, 0.4504, 0.5655, 0.9268],
        [0.2542, 0.4736, 0.7032, 0.7664, 0.0179, 0.2577, 0.8731]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
tensor_B = torch.rand(1, 7)
tensor_A = torch.rand(1, 7)

# Perform matrix multiplication
output = torch.matmul(tensor_A, tensor_B.T)
output 


tensor([[2.4374]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [16]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor_A = torch.rand(7, 5)
tensor_B = torch.rand(5, 1)


# Matrix multiply tensors
output = torch.matmul(tensor_A, tensor_B)
output, output.shape

(tensor([[0.5816],
         [1.7545],
         [0.4557],
         [1.2315],
         [1.5248],
         [0.6606],
         [0.6742]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [12]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
# Create two random tensors on GPU
tensor_A = torch.rand(2, 3).to(device)
tensor_B = torch.rand(2, 3).to(device)

tensor_A,tensor_A.device, tensor_B  ,tensor_B.device

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 device(type='cpu'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]),
 device(type='cpu'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [22]:
# Perform matmul on tensor_A and tensor_B
output=  tensor_A @ tensor_B.T
output, output.device

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]]),
 device(type='cpu'))

### 8. Find the maximum and minimum values of the output of 7.

In [27]:
# Find max
tensor = torch.arange(1, 7)
max_value = tensor.max()
print(max_value)
# Find min
min_value = tensor.min()
print(min_value)

tensor(6)
tensor(1)


### 9. Find the maximum and minimum index values of the output of 7.

In [28]:
# Find arg max
print(tensor.argmax())

# Find arg min
print(tensor.argmin())


tensor(5)
tensor(0)



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [31]:
# Set seed
torch.manual_seed(7)
# Create random tensor

tensor = torch.rand(1,1,1, 10)

# Remove single dimensions
tensor_squeezed = tensor.squeeze()

# Print out tensors and their shapes
print(tensor, tensor.shape)
print(tensor_squeezed, tensor_squeezed.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
